In [1]:
import numpy as np
import pandas as pd

In [5]:
#1. Array Creation:
#Question: Create a NumPy array containing the numbers from 0 to 9. What is the shape and data type of this array?

numbers = np.arange(10)
print(numbers)
print(numbers.shape)
print(type(numbers))

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.ndarray'>


In [5]:
#2. Array Shape:
#Question: Create a 2D array with shape (3, 4) filled with random integers between 0 and 10. What is the shape of the resulting array?
import numpy as np
twodarray= np.random.randint(0,10,size=(3,4))
print(twodarray)
print(twodarray.shape)

[[1 7 0 7]
 [5 3 6 1]
 [1 9 6 4]]
(3, 4)


In [7]:
#3. Array Reshaping:
#Question: Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]), reshape it into a 2x4 matrix.

arr = np.array([1,2,3,4,5,6,7,8])
reshape_array = arr.reshape(2,4)
print(reshape_array)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#4. Array Indexing:
#Question: From the following 2D array, extract the element in the 2nd row and 3rd column:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [12]:
#5. Slicing:
#Question: Given a 1D array arr = np.arange(10), extract the elements from index 2 to index 6 (not inclusive).

arr = np.arange(10)
print(arr)
print(arr[2:6])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [14]:
#6. Element-wise Operations:
#Question: Create two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Perform element-wise addition, subtraction, and multiplication.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [15]:
#Question: Add a scalar value of 10 to each element of the array arr = np.array([1, 2, 3, 4, 5]) using broadcasting.
arr = np.array([1,2,3,4,5])
print(arr + 10)

[11 12 13 14 15]


In [18]:
#8. Basic Statistical Operations:
#Question: Create a NumPy array of 15 random integers between 0 and 50. Find the mean, median, and standard deviation of the array.
arr = np.random.randint(0,50,size=15)
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

[42 26 14  1 24 42 44 20 15 22 32 12 20  7 18]
22.6
20.0
12.387090053761618


In [20]:
#9. Boolean Indexing:
#Question: From the array arr = np.array([10, 20, 30, 40, 50]), extract all elements greater than 25.
arr = np.array([10,20,30,40,50])
extracted_array = arr[arr>25]
print(extracted_array)

[30 40 50]


In [22]:
#10. Array Concatenation:
#Question: Create two arrays arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Concatenate them into a single array.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


# DataFrame Creation:


In [28]:
"""1. DataFrame Creation:
#Question: Create a Pandas DataFrame from the following dictionary:

data = {"name":['Alice','Bob','Charlie','David'],
'Age':[25,30,35,40],'City':['New York','Los Angeles','Chicago','Houston']}

Task 1: Display the DataFrame 
Task 2: Save it as “data.csv”"""

import pandas as pd

data = {"name":['Alice','Bob','Charlie','David'],
'Age':[25,30,35,40],
'City':['New York','Los Angeles','Chicago','Houston']}

df = pd.DataFrame(data)
print(df)
df.to_csv('data.csv',index = False)

      name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


In [29]:
df = pd.read_csv("data.csv")
print(df.head())

      name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


3. Selecting a Column:
Question: From the loaded data, select and display the "Name" column.

In [30]:
print(df['name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: name, dtype: object


In [32]:
#4. Filtering Rows:
#Question: From the above DataFrame, filter and display only the rows where the "Age" is greater than 30.
greater_than_30 = df[df['Age']>30]
print(greater_than_30)

      name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston


In [33]:
#5. Adding a New Column:
#Question: Add a new column named "Salary" to the DataFrame with the values [50000, 60000, 70000, 80000].
salary = [50000,60000,70000,80000]
df['Salary'] = salary
print(df)

      name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
